# Generated by Django 5.1 on 2025-12-30 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoodleUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Usuario')),
                ('firstname', models.CharField(max_length=100, verbose_name='Nombre')),
                ('lastname', models.CharField(max_length=100, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Usuario de Moodle',
                'verbose_name_plural': 'Usuarios de Moodle',
                'ordering': ['lastname', 'firstname'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('path', models.CharField(blank=True, max_length=500, verbose_name='Ruta')),
                ('depth', models.IntegerField(default=0, verbose_name='Profundidad')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='moodle.category', verbose_name='Categoría padre')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['path', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortname', models.CharField(max_length=255, unique=True, verbose_name='Código')),
                ('fullname', models.CharField(max_length=500, verbose_name='Nombre completo')),
                ('startdate', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('enddate', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='moodle.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['shortname'],
            },
        ),
        migrations.CreateModel(
            name='Enrol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrol', models.CharField(choices=[('manual', 'Manual'), ('self', 'Auto-inscripción'), ('cohort', 'Cohorte')], default='manual', max_length=50, verbose_name='Método')),
                ('status', models.BooleanField(default=True, verbose_name='Activo')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrol_methods', to='moodle.course', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Método de inscripción',
                'verbose_name_plural': 'Métodos de inscripción',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='moodle.course', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'ordering': ['course', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeadded', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de incorporación')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='moodle.group', verbose_name='Grupo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='moodle.moodleuser', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Miembro de grupo',
                'verbose_name_plural': 'Miembros de grupos',
                'unique_together': {('group', 'user')},
            },
        ),
        migrations.CreateModel(
            name='UserEnrolment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestart', models.DateTimeField(blank=True, null=True, verbose_name='Inicio')),
                ('timeend', models.DateTimeField(blank=True, null=True, verbose_name='Fin')),
                ('timecreated', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('enrol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_enrolments', to='moodle.enrol', verbose_name='Método de inscripción')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolments', to='moodle.moodleuser', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Inscripción de usuario',
                'verbose_name_plural': 'Inscripciones de usuarios',
                'unique_together': {('enrol', 'user')},
            },
        ),
        migrations.CreateModel(
            name='UserLastAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeaccess', models.DateTimeField(verbose_name='Último acceso')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='moodle.course', verbose_name='Curso')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_accesses', to='moodle.moodleuser', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Último acceso al curso',
                'verbose_name_plural': 'Últimos accesos a cursos',
                'indexes': [models.Index(fields=['course', 'timeaccess'], name='moodle_user_course__689d49_idx'), models.Index(fields=['user', 'timeaccess'], name='moodle_user_user_id_54a392_idx')],
                'unique_together': {('user', 'course')},
            },
        ),
    ]
