# Generated by Django 5.1 on 2025-12-30 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('shortname', models.CharField(choices=[('student', 'Estudiante'), ('teacher', 'Profesor'), ('editingteacher', 'Profesor editor'), ('manager', 'Gestor')], default='student', max_length=100, verbose_name='Código')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timecreated', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='moodle.course', verbose_name='Curso')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='moodle.role', verbose_name='Rol')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='moodle.moodleuser', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Asignación de rol',
                'verbose_name_plural': 'Asignaciones de roles',
                'unique_together': {('role', 'user', 'course')},
            },
        ),
    ]
