# Generated by Django 5.1 on 2025-12-30 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('analysis_type', models.CharField(max_length=50, verbose_name='Tipo de análisis')),
                ('parameters', models.JSONField(verbose_name='Parámetros')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Análisis guardado',
                'verbose_name_plural': 'Análisis guardados',
                'ordering': ['-created_at'],
            },
        ),
    ]
