# Generated by Django 5.2.9 on 2025-12-06 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moodle_id', models.IntegerField(unique=True, verbose_name='ID Moodle')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('parent', models.IntegerField(verbose_name='Categoría padre')),
                ('path', models.CharField(max_length=255, verbose_name='Ruta')),
                ('visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='Importado el')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moodle_id', models.IntegerField(unique=True, verbose_name='ID Moodle')),
                ('contextlevel', models.IntegerField(verbose_name='Nivel de contexto')),
                ('instanceid', models.IntegerField(verbose_name='ID Instancia')),
                ('path', models.CharField(max_length=255, verbose_name='Ruta')),
                ('depth', models.IntegerField(verbose_name='Profundidad')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='Importado el')),
            ],
            options={
                'verbose_name': 'Contexto',
                'verbose_name_plural': 'Contextos',
                'ordering': ['contextlevel', 'instanceid'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moodle_id', models.IntegerField(unique=True, verbose_name='ID Moodle')),
                ('shortname', models.CharField(max_length=255, verbose_name='Nombre corto')),
                ('fullname', models.CharField(max_length=255, verbose_name='Nombre completo')),
                ('category', models.IntegerField(verbose_name='Categoría')),
                ('startdate', models.IntegerField(verbose_name='Fecha inicio (timestamp)')),
                ('enddate', models.IntegerField(verbose_name='Fecha fin (timestamp)')),
                ('visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='Importado el')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['shortname'],
            },
        ),
        migrations.CreateModel(
            name='Enrol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moodle_id', models.IntegerField(unique=True, verbose_name='ID Moodle')),
                ('courseid', models.IntegerField(verbose_name='ID Curso')),
                ('enrol', models.CharField(max_length=50, verbose_name='Método')),
                ('status', models.IntegerField(verbose_name='Estado')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='Importado el')),
            ],
            options={
                'verbose_name': 'Método de Inscripción',
                'verbose_name_plural': 'Métodos de Inscripción',
                'ordering': ['courseid', 'enrol'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moodle_id', models.IntegerField(unique=True, verbose_name='ID Moodle')),
                ('courseid', models.IntegerField(verbose_name='ID Curso')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('idnumber', models.CharField(blank=True, max_length=100, verbose_name='Número ID')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='Importado el')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'ordering': ['courseid', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moodle_id', models.IntegerField(unique=True, verbose_name='ID Moodle')),
                ('groupid', models.IntegerField(verbose_name='ID Grupo')),
                ('userid', models.IntegerField(verbose_name='ID Usuario')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='Importado el')),
            ],
            options={
                'verbose_name': 'Miembro de Grupo',
                'verbose_name_plural': 'Miembros de Grupos',
                'ordering': ['groupid', 'userid'],
            },
        ),
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=100, verbose_name='Tabla')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Inicio')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin')),
                ('records_imported', models.IntegerField(default=0, verbose_name='Registros importados')),
                ('status', models.CharField(choices=[('running', 'En progreso'), ('completed', 'Completada'), ('failed', 'Fallida')], default='running', max_length=20, verbose_name='Estado')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de error')),
            ],
            options={
                'verbose_name': 'Log de Importación',
                'verbose_name_plural': 'Logs de Importación',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moodle_id', models.IntegerField(unique=True, verbose_name='ID Moodle')),
                ('roleid', models.IntegerField(verbose_name='ID Rol')),
                ('contextid', models.IntegerField(verbose_name='ID Contexto')),
                ('userid', models.IntegerField(verbose_name='ID Usuario')),
                ('timemodified', models.IntegerField(verbose_name='Modificado (timestamp)')),
                ('modifierid', models.IntegerField(verbose_name='ID Modificador')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='Importado el')),
            ],
            options={
                'verbose_name': 'Asignación de Rol',
                'verbose_name_plural': 'Asignaciones de Roles',
                'ordering': ['userid', 'roleid'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moodle_id', models.IntegerField(unique=True, verbose_name='ID Moodle')),
                ('username', models.CharField(max_length=100, verbose_name='Nombre de usuario')),
                ('firstname', models.CharField(max_length=100, verbose_name='Nombre')),
                ('lastname', models.CharField(max_length=100, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('country', models.CharField(blank=True, max_length=2, verbose_name='País')),
                ('suspended', models.BooleanField(default=False, verbose_name='Suspendido')),
                ('deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='Importado el')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['lastname', 'firstname'],
            },
        ),
        migrations.CreateModel(
            name='UserEnrolment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moodle_id', models.IntegerField(unique=True, verbose_name='ID Moodle')),
                ('userid', models.IntegerField(verbose_name='ID Usuario')),
                ('enrolid', models.IntegerField(verbose_name='ID Inscripción')),
                ('timestart', models.IntegerField(verbose_name='Inicio (timestamp)')),
                ('timeend', models.IntegerField(verbose_name='Fin (timestamp)')),
                ('status', models.IntegerField(verbose_name='Estado')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='Importado el')),
            ],
            options={
                'verbose_name': 'Inscripción de Usuario',
                'verbose_name_plural': 'Inscripciones de Usuarios',
                'ordering': ['userid', 'enrolid'],
            },
        ),
        migrations.CreateModel(
            name='UserLastAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moodle_id', models.IntegerField(unique=True, verbose_name='ID Moodle')),
                ('userid', models.IntegerField(verbose_name='ID Usuario')),
                ('courseid', models.IntegerField(verbose_name='ID Curso')),
                ('timeaccess', models.IntegerField(verbose_name='Tiempo acceso (timestamp)')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='Importado el')),
            ],
            options={
                'verbose_name': 'Último Acceso de Usuario',
                'verbose_name_plural': 'Últimos Accesos de Usuarios',
                'ordering': ['-timeaccess'],
            },
        ),
    ]
